project:
  type: website
  output-dir: docs
  

website:
  title: "bndlev001Assignment1"
  navbar:
    left:
      - href: Assignment1.qmd
        text: Assignment 
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

