project:
  type: website
  output-dir: docs
  

website:
  title: "SONA South Africa"
  navbar:
    left:
      - href: Assignment1.qmd
        text: Content

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

